version: "3.4"

services:
  taka-worker-sync:
    image: taka-worker-sync-test
    build:
      target: test
      context: ../../
      dockerfile: Workers/Taka.Worker.Sync/Dockerfile-test
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - /home/runner/work/_temp:/root/.kube
    entrypoint: dotnet watch run --verbose --no-launch-profile --configuration Debug
    ports:
      - "5003:80"
