FROM mmercan/dockerfile-sonarqube-dotnet50-sdk:latest AS test
ARG buildtime_APPID
ARG buildtime_APPSECRET
ARG buildtime_ADID
ARG buildtime_SONARKEY
# ENV DOTNET_USE_POLLING_FILE_WATCHER=1
# ENV ASPNETCORE_ENVIRONMENT=Development
# ENV SONAR_HOST http://sonar.myrcan.com
# RUN apt-get update && apt-get install -y openjdk-8-jdk
# RUN dotnet tool install --global dotnet-sonarscanner
# ENV PATH="${PATH}:/root/.dotnet/tools"
ENV ASPNETCORE_URLS=http://+:80
ENV PROJECT=Taka.Worker.Sync
ENV VERSION=1.0
ENV SONARKEY=$buildtime_SONARKEY
ENV APPID=$buildtime_APPID
ENV APPSECRET=$buildtime_APPSECRET
ENV ADID=$buildtime_ADID
ENV SONAR_HOST=https://sonarcloud.io

WORKDIR /src
COPY Workers/Taka.Worker.Sync/Taka.Worker.Sync.csproj Workers/Taka.Worker.Sync/
RUN dotnet restore Workers/Taka.Worker.Sync/Taka.Worker.Sync.csproj
COPY . .
RUN dotnet sonarscanner begin /k:$PROJECT /v:$VERSION /d:sonar.host.url=$SONAR_HOST /o:mmercan-github /d:sonar.login=$SONARKEY  /d:sonar.cs.opencover.reportsPaths="/TestResults/coverage.opencover.xml" /d:sonar.exclusions="**bootstrap.css, **bootstrap-reboot.css, **bootstrap.js, **/wwwroot/**, **Empty.Tests" /d:sonar.coverage.exclusions="**Tests*.cs, **.js," /d:sonar.cs.vstest.reportsPaths="/TestResults/*.trx"
RUN dotnet build ./Workers/Taka.Worker.Sync/Taka.Worker.Sync.sln

# RUN dotnet test ./Workers/Taka.Worker.Sync/Taka.Worker.Sync.sln   /p:CollectCoverage=true /p:CoverletOutput=/TestResults/ /p:MergeWith=/TestResults/coverage.json --logger=trx -r /TestResults/
# RUN dotnet test ./Empty.Tests/Empty.Tests.sln /p:CollectCoverage=true /p:MergeWith="/TestResults/coverage.json" /p:CoverletOutputFormat="opencover" /p:CoverletOutput=/TestResults/

# RUN dotnet build-server shutdown
# RUN dotnet sonarscanner end /d:sonar.login=$SONARKEY

ENTRYPOINT ["./Workers/Taka.Worker.Sync/commands.sh"]