version: "3.8"

services:
  taka-worker-sync:
    image: mmercan/taka-worker-sync
    build:
      target: final
      context: ../../
      dockerfile: Workers/Taka.Worker.Sync/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    # ports:
    #   - "5005:80"
