name: Taka.Worker.Sync CI

on:
  push:
    branches: [master]
    paths:
      - Workers/Taka.Worker.Sync/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-test-aks2

      - name: add KUBECONFIG To env file
        run: |
          cp ${{ env.KUBECONFIG }} /home/runner/work/_temp/config

      - name: View Docker Compose config
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose-test.yml --log-level DEBUG config

      - name: Build Test Docker Compose file
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose-test.yml --log-level DEBUG build \
          --build-arg buildtime_APPID=${{ secrets.buildtime_APPID }} \
          --build-arg buildtime_APPSECRET=${{ secrets.buildtime_APPSECRET }} \
          --build-arg buildtime_ADID=${{ secrets.buildtime_ADID }}$() \
          --build-arg buildtime_SONARKEY=${{ secrets.buildtime_SONARKEY }} \

      - name: Run the Test image
        run: docker run -i -v ${{env.ARTIFACT_PATH}}/TestResults:/TestResults taka-worker-sync-test

      - name: Build the Docker image
        run: docker build . --file Workers/Taka.Worker.Sync/Dockerfile --tag my-image-name:$(date +%s)

      - name: Build Docker Compose file
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose.yml build \

      - name: Tag the Image
        run: |
          docker tag mmercan/taka-worker-sync:latest mmercan/taka-worker-sync:${{ github.run_id }}-prod-linux

      - name: Push Docker Images
        run: |
          docker push mmercan/taka-worker-sync --all-tags \

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: TestResults

      - name: Archive helm charts
        uses: actions/upload-artifact@v2
        with:
          name: helm
          path: Helm
  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    env:
      chartName: "healthmonitoring-api"
      namespace: "taka-dev"
      releaseName: "taka-dev-sync-worker"
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
      WorkflowRunURL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      EventName: $GITHUB_EVENT_NAME
      TriggerActor: $GITHUB_ACTOR
      GitCommitURL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA
      GitRef: $GITHUB_REF
      GitPullReqRef: $GITHUB_HEAD_REF

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: helm

      - name: helm version
        run: |
          helm version
          echo ${{ env.WorkflowRunURL }}
          echo ${{ env.EventName }}
          echo ${{ env.TriggerActor }}
          echo ${{ env.GitCommitURL }}
          echo ${{ env.GitRef }}
          echo ${{ env.GitPullReqRef }}

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          context: matt-test-aks2

      - name: List all folders
        run: |
          ls -R \

      - name: helm package
        run: |
          helm package \
          --version 2.0.0-$GITHUB_RUN_ID \
          --destination $GITHUB_WORKSPACE/package \
          $GITHUB_WORKSPACE/Taka/charts/Taka.Worker.Sync \

      - name: helm template
        run: |
          helm template \
          $GITHUB_WORKSPACE/Taka/charts/Taka.Worker.Sync \
          -f $GITHUB_WORKSPACE/values/Taka.Worker.Sync/dev-values.yaml \

      - name: helm version
        run: |
          kubectl get namespaces \
