name: Taka.Worker.Sync CI

on:
  push:
    branches: [master]
    paths:
      - Workers/Taka.Worker.Sync/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Compose file
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose-test.yml build \
          --build-arg buildtime_APPID=${{ secrets.buildtime_APPID }} \
          --build-arg buildtime_APPSECRET=${{ secrets.buildtime_APPSECRET }} \
          --build-arg buildtime_ADID=${{ secrets.buildtime_ADID }}$() \
          --build-arg buildtime_SONARKEY=${{ secrets.buildtime_SONARKEY }} \

      - name: Tag the Image
        run: docker tag taka-worker-sync-test:latest imagename:${{ github.run_id }}

      - name: Build the Docker image
        run: docker build . --file Workers/Taka.Worker.Sync/Dockerfile --tag my-image-name:$(date +%s)
