name: Taka.Worker.Sync CI

on:
  push:
    branches: [master]
    paths:
      - Workers/Taka.Worker.Sync/**
  pull_request:
    branches: [master]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_PATH: ${{ github.workspace }}
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Test Docker Compose file
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose-test.yml build \
          --build-arg buildtime_APPID=${{ secrets.buildtime_APPID }} \
          --build-arg buildtime_APPSECRET=${{ secrets.buildtime_APPSECRET }} \
          --build-arg buildtime_ADID=${{ secrets.buildtime_ADID }}$() \
          --build-arg buildtime_SONARKEY=${{ secrets.buildtime_SONARKEY }} \

      - name: Run the Test image
        run: docker run -i -v ${{env.ARTIFACT_PATH}}:/TestResults taka-worker-sync-test

      - name: Build the Docker image
        run: docker build . --file Workers/Taka.Worker.Sync/Dockerfile --tag my-image-name:$(date +%s)

      - name: Build Docker Compose file
        run: |
          docker-compose --file Workers/Taka.Worker.Sync/docker-compose.yml build \

      - name: Tag the Image
        run: |
          docker tag mmercan/taka-worker-sync:latest mmercan/taka-worker-sync:${{ github.run_id }}-prod-linux

      - name: Push Docker Images
        run: |
          docker push mmercan/taka-worker-sync --all-tags \

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: TestResults
